global:
  scrape_interval: 60s

scrape_configs:
  - job_name: laravel_apps
    scrape_interval: 60s
    metrics_path: /prometheus
    scheme: https
    static_configs:
      - targets:
          - website-1.com
          - website-2.com
          - website-3.com # Do not use Https with any domain. Simple domain E.g youtube.com, theprimehq.com